export const personal = [
  {
    id: 10,
    firstName: "Marian",
    lastName: "Pop",
    title: "Medic Veterinar Primar",
    email: "m.pop@tomvet.com",
    image: "./images/personal.jpg",
    phone: "0722222222",
    isPersonal: true,
    address: {
      str: "lalelelor",
      nr: "25",
      city: "Timisoara",
      county: "Timis",
      postalCode: "123456",
    },
  },
  {
    id: 10,
    firstName: "Marian",
    lastName: "Pop",
    title: "Medic Veterinar Primar",
    email: "m.pop@tomvet.com",
    image: "./images/personal.jpg",
    phone: "0722222222",
    isPersonal: true,
    address: {
      str: "lalelelor",
      nr: "25",
      city: "Timisoara",
      county: "Timis",
      postalCode: "123456",
    },
  },
  {
    id: 10,
    firstName: "Marian",
    lastName: "Pop",
    title: "Medic Veterinar Primar",
    email: "m.pop@tomvet.com",
    image: "./images/personal.jpg",
    phone: "0722222222",
    isPersonal: true,
    address: {
      str: "lalelelor",
      nr: "25",
      city: "Timisoara",
      county: "Timis",
      postalCode: "123456",
    },
  },
];
