# Generated by Django 4.2.4 on 2023-08-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='wheat.png', upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sell_by', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=255)),
                ('count_in_stock', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
